# Default configurations
defaults:
  - dataset: cifar10
  - model: sew_resnet
  - optimizer: sgd

# Learning rate scheduler configuration
scheduler:
  name: CosineAnnealingLR
  params:
    T_max: ${max_epochs}

# Data loading configuration
data_loader:
  batch_size: 128
  num_workers: 8

# Training configuration
devices: [0]
max_epochs: 400
precision: '16-mixed'

# Logging configuration
wandb:
  entity: ritianzhaoxx
  run_name: test

# Model-specific configuration
T: 4  # Number of time steps for SNN
loss: cross_entropy

# Optimization configuration
compile: True  # Use torch.compile for acceleration
to_pytorch: True  # Convert to PyTorch model

# Reproducibility
seed: 42

# Experiment tracking
use_wandb: True

# Data augmentation
autoaugment: True

# Debugging
debug: False  # Control the number of sanity validation steps